# ROFL-Compatible Docker Compose Configuration
# Resource-optimized for 512MB RAM, 1 CPU (70% cost reduction)
version: "3.8"

services:
  funding-arbitrage:
    build: .
    image: "bioharz/nyancat-finance"
    platform: linux/amd64
    container_name: rofl-funding-arbitrage

    # Resource limits (optimized for cost)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.5"

    # Environment variables
    environment:
      - NODE_ENV=production
      - ROFL_MODE=false
      - DATA_DIR=/app/data
      - RESULTS_DIR=/app/results
      
      # Graph Protocol Integration - ENABLED BY DEFAULT
      - ENABLE_GRAPH_UPLOAD=true
      - GRAPH_NETWORK=TESTNET
      - GRAPH_API_URL=https://hypergraph-v2-testnet.up.railway.app
      - GRAPH_IPFS_URL=https://ipfs.hypergraph.xyz
      
      # Load Graph Protocol credentials from host .env file
      - PRIVATE_KEY=${PRIVATE_KEY}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - SPACE_ID=${SPACE_ID:-}
      - SPACE_NAME=${SPACE_NAME:-ROFL Demo Results}

    # Persistent storage volumes
    volumes:
      - historical_cache:/app/data/historical
      - demo_results:/app/results
      - rofl_config:/app/config

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

    # Network configuration
    networks:
      - rofl-network

    # Security context
    security_opt:
      - no-new-privileges:true

    # ROFL-specific labels
    labels:
      - "rofl.app=funding-arbitrage"
      - "rofl.version=1.0.0"
      - "rofl.budget=150TEST"
      - "rofl.storage=persistent"

# Named volumes for persistent storage
volumes:
  historical_cache:
    driver: local

  demo_results:
    driver: local

  rofl_config:
    driver: local

# Network configuration
networks:
  rofl-network:
    driver: bridge
    labels:
      - "rofl.network=secure"
