// Top 30 liquid pairs with both spot and perpetual markets on Bybit
export const TOP_30_VALID_PAIRS = [
  'BTC/USDT:USDT',    // Bitcoin
  'ETH/USDT:USDT',    // Ethereum
  'SOL/USDT:USDT',    // Solana
  'BNB/USDT:USDT',    // Binance Coin
  'XRP/USDT:USDT',    // Ripple
  'DOGE/USDT:USDT',   // Dogecoin
  'ADA/USDT:USDT',    // Cardano
  'AVAX/USDT:USDT',   // Avalanche
  'DOT/USDT:USDT',    // Polkadot
  'POL/USDT:USDT',    // Polygon (formerly MATIC)
  'LINK/USDT:USDT',   // Chainlink
  'TRX/USDT:USDT',    // Tron
  'NEAR/USDT:USDT',   // Near Protocol
  'LTC/USDT:USDT',    // Litecoin
  'BCH/USDT:USDT',    // Bitcoin Cash
  'ARB/USDT:USDT',    // Arbitrum
  'OP/USDT:USDT',     // Optimism
  'UNI/USDT:USDT',    // Uniswap
  'ATOM/USDT:USDT',   // Cosmos
  'XLM/USDT:USDT',    // Stellar
  'FIL/USDT:USDT',    // Filecoin
  'AAVE/USDT:USDT',   // Aave
  'MKR/USDT:USDT',    // Maker
  'LDO/USDT:USDT',    // Lido DAO
  'CRV/USDT:USDT',    // Curve
  'WLD/USDT:USDT',    // Worldcoin
  'RENDER/USDT:USDT', // Render Token
  'INJ/USDT:USDT',    // Injective
  'SUI/USDT:USDT',    // Sui
  'WIF/USDT:USDT'     // dogwifhat
];

// All 304 valid pairs (for future use)
export const ALL_VALID_PAIRS = [
  '1INCH/USDT:USDT', 'A/USDT:USDT', 'A8/USDT:USDT', 'AAVE/USDT:USDT', 'ACH/USDT:USDT',
  'ADA/USDT:USDT', 'AERO/USDT:USDT', 'AEVO/USDT:USDT', 'AGI/USDT:USDT', 'AGLD/USDT:USDT',
  'AI16Z/USDT:USDT', 'AIOZ/USDT:USDT', 'AIXBT/USDT:USDT', 'ALCH/USDT:USDT', 'ALGO/USDT:USDT',
  'ALT/USDT:USDT', 'ANIME/USDT:USDT', 'ANKR/USDT:USDT', 'APE/USDT:USDT', 'APT/USDT:USDT',
  'AR/USDT:USDT', 'ARB/USDT:USDT', 'ARKM/USDT:USDT', 'ATH/USDT:USDT', 'ATOM/USDT:USDT',
  'AVA/USDT:USDT', 'AVAIL/USDT:USDT', 'AVAX/USDT:USDT', 'AVL/USDT:USDT', 'AXL/USDT:USDT',
  'AXS/USDT:USDT', 'B3/USDT:USDT', 'BAN/USDT:USDT', 'BAT/USDT:USDT', 'BB/USDT:USDT',
  'BCH/USDT:USDT', 'BDXN/USDT:USDT', 'BEAM/USDT:USDT', 'BEL/USDT:USDT', 'BERA/USDT:USDT',
  'BICO/USDT:USDT', 'BLAST/USDT:USDT', 'BLUR/USDT:USDT', 'BMT/USDT:USDT', 'BNB/USDT:USDT',
  'BOBA/USDT:USDT', 'BOME/USDT:USDT', 'BR/USDT:USDT', 'BRETT/USDT:USDT', 'BTC/USDT:USDT',
  'C98/USDT:USDT', 'CAKE/USDT:USDT', 'CARV/USDT:USDT', 'CATI/USDT:USDT', 'CELO/USDT:USDT',
  'CGPT/USDT:USDT', 'CHILLGUY/USDT:USDT', 'CHZ/USDT:USDT', 'CLOUD/USDT:USDT', 'COMP/USDT:USDT',
  'COOK/USDT:USDT', 'COOKIE/USDT:USDT', 'CORE/USDT:USDT', 'CPOOL/USDT:USDT', 'CRV/USDT:USDT',
  'CTC/USDT:USDT', 'CUDIS/USDT:USDT', 'CYBER/USDT:USDT', 'DBR/USDT:USDT', 'DEEP/USDT:USDT',
  'DEGEN/USDT:USDT', 'DGB/USDT:USDT', 'DOGE/USDT:USDT', 'DOGS/USDT:USDT', 'DOOD/USDT:USDT',
  'DOT/USDT:USDT', 'DRIFT/USDT:USDT', 'DYDX/USDT:USDT', 'DYM/USDT:USDT', 'EGLD/USDT:USDT',
  'EIGEN/USDT:USDT', 'ELX/USDT:USDT', 'ENA/USDT:USDT', 'ENJ/USDT:USDT', 'ENS/USDT:USDT',
  'EPT/USDT:USDT', 'ETC/USDT:USDT', 'ETH/USDT:USDT', 'ETHFI/USDT:USDT', 'ETHW/USDT:USDT',
  'F/USDT:USDT', 'FHE/USDT:USDT', 'FIDA/USDT:USDT', 'FIL/USDT:USDT', 'FLOCK/USDT:USDT',
  'FLOW/USDT:USDT', 'FLR/USDT:USDT', 'FRAG/USDT:USDT', 'FUEL/USDT:USDT', 'FXS/USDT:USDT',
  'G/USDT:USDT', 'GALA/USDT:USDT', 'GLMR/USDT:USDT', 'GMT/USDT:USDT', 'GMX/USDT:USDT',
  'GOAT/USDT:USDT', 'GODS/USDT:USDT', 'GPS/USDT:USDT', 'GRASS/USDT:USDT', 'GRT/USDT:USDT',
  'H/USDT:USDT', 'HAEDAL/USDT:USDT', 'HBAR/USDT:USDT', 'HFT/USDT:USDT', 'HMSTR/USDT:USDT',
  'HNT/USDT:USDT', 'HOME/USDT:USDT', 'HOOK/USDT:USDT', 'HPOS10I/USDT:USDT', 'HUMA/USDT:USDT',
  'HYPER/USDT:USDT', 'ICNT/USDT:USDT', 'ICP/USDT:USDT', 'ICX/USDT:USDT', 'ID/USDT:USDT',
  'IMX/USDT:USDT', 'INIT/USDT:USDT', 'INJ/USDT:USDT', 'IO/USDT:USDT', 'IP/USDT:USDT',
  'J/USDT:USDT', 'JASMY/USDT:USDT', 'JST/USDT:USDT', 'JTO/USDT:USDT', 'JUP/USDT:USDT',
  'KAIA/USDT:USDT', 'KAS/USDT:USDT', 'KAVA/USDT:USDT', 'KDA/USDT:USDT', 'KMNO/USDT:USDT',
  'KSM/USDT:USDT', 'L3/USDT:USDT', 'LA/USDT:USDT', 'LDO/USDT:USDT', 'LINK/USDT:USDT',
  'LOOKS/USDT:USDT', 'LRC/USDT:USDT', 'LTC/USDT:USDT', 'MAGIC/USDT:USDT', 'MAJOR/USDT:USDT',
  'MANA/USDT:USDT', 'MANTA/USDT:USDT', 'MASA/USDT:USDT', 'MASK/USDT:USDT', 'MAVIA/USDT:USDT',
  'MBOX/USDT:USDT', 'ME/USDT:USDT', 'MEME/USDT:USDT', 'MERL/USDT:USDT', 'MEW/USDT:USDT',
  'MILK/USDT:USDT', 'MINA/USDT:USDT', 'MKR/USDT:USDT', 'MNT/USDT:USDT', 'MOCA/USDT:USDT',
  'MORPHO/USDT:USDT', 'MOVE/USDT:USDT', 'MOVR/USDT:USDT', 'MVL/USDT:USDT', 'MYRIA/USDT:USDT',
  'MYRO/USDT:USDT', 'NEAR/USDT:USDT', 'NEWT/USDT:USDT', 'NOT/USDT:USDT', 'NS/USDT:USDT',
  'NXPC/USDT:USDT', 'OBOL/USDT:USDT', 'OBT/USDT:USDT', 'OL/USDT:USDT', 'OM/USDT:USDT',
  'OMNI/USDT:USDT', 'ONDO/USDT:USDT', 'ONE/USDT:USDT', 'OP/USDT:USDT', 'ORDER/USDT:USDT',
  'ORDI/USDT:USDT', 'PARTI/USDT:USDT', 'PENDLE/USDT:USDT', 'PENGU/USDT:USDT', 'PEOPLE/USDT:USDT',
  'PERP/USDT:USDT', 'PLUME/USDT:USDT', 'PNUT/USDT:USDT', 'POL/USDT:USDT', 'PONKE/USDT:USDT',
  'POPCAT/USDT:USDT', 'PORTAL/USDT:USDT', 'PRCL/USDT:USDT', 'PRIME/USDT:USDT', 'PUFFER/USDT:USDT',
  'PUMPBTC/USDT:USDT', 'PYTH/USDT:USDT', 'QNT/USDT:USDT', 'QTUM/USDT:USDT', 'RDNT/USDT:USDT',
  'RED/USDT:USDT', 'RENDER/USDT:USDT', 'RESOLV/USDT:USDT', 'ROAM/USDT:USDT', 'ROSE/USDT:USDT',
  'RPL/USDT:USDT', 'RSS3/USDT:USDT', 'RUNE/USDT:USDT', 'RVN/USDT:USDT', 'S/USDT:USDT',
  'SAFE/USDT:USDT', 'SAHARA/USDT:USDT', 'SAND/USDT:USDT', 'SAROS/USDT:USDT', 'SC/USDT:USDT',
  'SCA/USDT:USDT', 'SCR/USDT:USDT', 'SCRT/USDT:USDT', 'SD/USDT:USDT', 'SEI/USDT:USDT',
  'SEND/USDT:USDT', 'SERAPH/USDT:USDT', 'SIGN/USDT:USDT', 'SKATE/USDT:USDT', 'SLP/USDT:USDT',
  'SNX/USDT:USDT', 'SOL/USDT:USDT', 'SOLO/USDT:USDT', 'SOLV/USDT:USDT', 'SONIC/USDT:USDT',
  'SOSO/USDT:USDT', 'SPEC/USDT:USDT', 'SPELL/USDT:USDT', 'SPK/USDT:USDT', 'SPX/USDT:USDT',
  'SQD/USDT:USDT', 'SSV/USDT:USDT', 'STG/USDT:USDT', 'STRK/USDT:USDT', 'STX/USDT:USDT',
  'SUI/USDT:USDT', 'SUN/USDT:USDT', 'SUNDOG/USDT:USDT', 'SUSHI/USDT:USDT', 'SWEAT/USDT:USDT',
  'SWELL/USDT:USDT', 'SXT/USDT:USDT', 'TAI/USDT:USDT', 'TAIKO/USDT:USDT', 'THETA/USDT:USDT',
  'TIA/USDT:USDT', 'TNSR/USDT:USDT', 'TOKEN/USDT:USDT', 'TON/USDT:USDT', 'TRUMP/USDT:USDT',
  'TRX/USDT:USDT', 'TWT/USDT:USDT', 'UMA/USDT:USDT', 'UNI/USDT:USDT', 'USDC/USDT:USDT',
  'USDE/USDT:USDT', 'USTC/USDT:USDT', 'UXLINK/USDT:USDT', 'VANA/USDT:USDT', 'VANRY/USDT:USDT',
  'VELO/USDT:USDT', 'VET/USDT:USDT', 'VIC/USDT:USDT', 'VIRTUAL/USDT:USDT', 'VTHO/USDT:USDT',
  'VVV/USDT:USDT', 'W/USDT:USDT', 'WAL/USDT:USDT', 'WAVES/USDT:USDT', 'WAXP/USDT:USDT',
  'WCT/USDT:USDT', 'WIF/USDT:USDT', 'WLD/USDT:USDT', 'WOO/USDT:USDT', 'XAI/USDT:USDT',
  'XAUT/USDT:USDT', 'XDC/USDT:USDT', 'XEM/USDT:USDT', 'XION/USDT:USDT', 'XLM/USDT:USDT',
  'XRP/USDT:USDT', 'XTER/USDT:USDT', 'XTZ/USDT:USDT', 'YFI/USDT:USDT', 'ZEN/USDT:USDT',
  'ZENT/USDT:USDT', 'ZEREBRO/USDT:USDT', 'ZETA/USDT:USDT', 'ZIL/USDT:USDT', 'ZK/USDT:USDT',
  'ZORA/USDT:USDT', 'ZRC/USDT:USDT', 'ZRO/USDT:USDT', 'ZRX/USDT:USDT'
];